In [17]:
import numpy as np

In [18]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [19]:
print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [20]:
print y 

[[0]
 [1]
 [1]
 [0]]


In [21]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [22]:
print syn0

[[ 0.43751046 -0.87147249 -0.94693224  0.9885952 ]
 [ 0.06516416 -0.18533271 -0.98305236 -0.79570201]
 [ 0.33021975 -0.50428629 -0.14806062 -0.92693656]]


In [23]:
print syn1

[[-0.87358475]
 [ 0.72316592]
 [-0.82136008]
 [-0.54707628]]


In [24]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [28]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
    
    #in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta= l1_error * nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    

Error:0.0024877816751
Error:0.00237047294151
Error:0.00226766381512
Error:0.00217663017799
Error:0.00209531042399
Error:0.00202211238813
